# Generated by Django 2.2.28 on 2023-07-04 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='推送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='支持html格式的内容', verbose_name='通知内容')),
                ('get_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemnotification_recipient', to=settings.AUTH_USER_MODEL, verbose_name='收信人')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'ordering': ['-create_date'],
            },
        ),
    ]
