# Generated by Django 2.2.28 on 2024-08-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20230708_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
