# Generated by Django 2.2.28 on 2026-09-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentvariable',
            options={'ordering': ['-created_at'], 'verbose_name': '环境变量', 'verbose_name_plural': '环境变量'},
        ),
        migrations.AlterModelOptions(
            name='taskscript',
            options={'ordering': ['-created_at'], 'verbose_name': '脚本', 'verbose_name_plural': '脚本'},
        ),
    ]
