# Generated by Django 2.2.28 on 2023-07-02 11:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230702_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='friend/default.png', help_text='上传图片大小建议120x120以上，使用友联域名命名，如tendcode.com.png', upload_to='friend/%Y', verbose_name='网站LOGO'),
        ),
    ]
