# Generated by Django 2.2.28 on 2023-07-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230702_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-update_date'], 'verbose_name': '时间线', 'verbose_name_plural': '时间线'},
        ),
    ]
