# Generated by Django 2.2.28 on 2023-07-09 12:37

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230708_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlink',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='friend/default/default.png', help_text='上传图片大小建议120x120以上，使用友联域名命名，如tendcode.com.png', upload_to='friend/upload/%Y', verbose_name='网站LOGO'),
        ),
    ]
