# Generated by Django 2.2.28 on 2023-07-10 16:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230709_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='article/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', upload_to='article/upload/%Y/%m/%d/', verbose_name='封面图'),
        ),
    ]
