# Generated by Django 2.2.28 on 2023-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230715_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic_short_title',
            field=models.CharField(blank=True, help_text='专门给Topic使用的短标题', max_length=50, null=True, verbose_name='主题短标题'),
        ),
    ]
