# Generated by Django 2.2.28 on 2023-07-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230715_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['sort_order'], 'verbose_name': '专题', 'verbose_name_plural': '专题'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['sort_order'], 'verbose_name': '专题-主题', 'verbose_name_plural': '专题-主题'},
        ),
    ]
