# Generated by Django 2.2.28 on 2023-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230727_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='统计日期')),
                ('body', models.TextField(verbose_name='统计数据')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章浏览量统计',
                'verbose_name_plural': '文章浏览量统计',
                'ordering': ['create_date'],
            },
        ),
    ]
