# Generated by Django 2.2.28 on 2023-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_articleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='date',
            field=models.CharField(max_length=10, unique=True, verbose_name='统计日期'),
        ),
    ]
