# Generated by Django 2.2.28 on 2023-12-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20231208_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='页面地址')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面名称')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单页面浏览量',
                'verbose_name_plural': '单页面浏览量',
                'ordering': ['url'],
            },
        ),
    ]
