# Generated by Django 2.2.28 on 2023-12-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='is_compute',
            field=models.BooleanField(default=True, verbose_name='是否计算到访问量'),
        ),
    ]
