# Generated by Django 2.2.28 on 2024-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_pageview_is_compute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='feed地址')),
                ('icon', models.TextField(help_text='可以填写base64图片格式或者图标地址', verbose_name='图标地址')),
                ('is_active', models.BooleanField(default=True, help_text='作为是否采集的标识', verbose_name='是否有效')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('data', models.TextField(blank=True, help_text='定义任务采集数据', null=True, verbose_name='数据')),
            ],
            options={
                'verbose_name': 'Feed Hub',
                'verbose_name_plural': 'Feed Hub',
                'ordering': ['name'],
            },
        ),
    ]
