# Generated by Django 2.2.28 on 2024-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20240101_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：Github 主页', max_length=20, unique=True, verbose_name='名称')),
                ('icon', models.CharField(help_text='如：fa-github', max_length=20, unique=True, verbose_name='图标')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='链接')),
                ('title', models.CharField(help_text='外链的描述', max_length=50, unique=True, verbose_name='标题')),
                ('active', models.BooleanField(default=True, help_text='是展示有效的链接', verbose_name='是否有效')),
                ('sort_order', models.IntegerField(default=99, help_text='作为显示的时候的顺序', verbose_name='排序')),
            ],
            options={
                'verbose_name': '菜单外链',
                'verbose_name_plural': '菜单外链',
                'ordering': ['sort_order'],
            },
        ),
    ]
