# Generated by Django 2.2.28 on 2024-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_menulink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='content',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='描述'),
        ),
    ]
