# Generated by Django 2.2.28 on 2024-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20240409_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_data', models.TextField(help_text='配置项作为全局上下文使用，上下文的具体定义见 apps/blog/context_processors.py 文件\n请按JSON格式提供配置数据：\n{\n  "site_logo_name\': "TendCode",  # 必填，网站LOGO显示内容\n  "site_end_title\': "izone",  # 必填，网站标题结尾内容\n  "site_description": "这是一个个人博客",  # 必填，网站描述\n  "site_keywords": "Django博客,个人博客",  # 必填，网站关键词，多个用英文逗号拼接\n  "site_create_date": "2023-09-20",  # 必填，网站创建日期，必须是 %Y-%m-%d 格式\n  "site_github": "https://github.com/Hopetree",  # 建议填，个人 Github 地址\n  "site_http_type": "https",  # 建议填，使用 http 还是 https\n  "site_icp_number": "京ICP备XXXX号",  # 选填，备案号\n  "site_cnzz_protocol": "<script xxx </script>",  # 选填，站长统计（友盟）代码\n  "site_la51_protocol": "<script xxx </script>",  # 选填，站长统计（51.la）代码\n  "site_verification": "<meta xxx />",  # 选填，站长推送\n  "site_reward_wx": "https://xxxx.xxx",  # 选填，文章页面的微信打赏二维码图片地址\n  "site_reward_zfb": "https://xxxx.xxx",  # 选填，文章页面的支付宝打赏二维码图片地址\n}', verbose_name='配置数据')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
    ]
