# Generated by Django 2.2.28 on 2024-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(help_text='跑步开始时间', verbose_name='跑步时间')),
                ('training_duration', models.CharField(help_text='如：0:35:12', max_length=7, verbose_name='训练时长')),
                ('distance', models.FloatField(help_text='如：5.03', verbose_name='距离(公里)')),
                ('active_kcal', models.IntegerField(help_text='如：301', verbose_name='动态千卡')),
                ('total_kcal', models.IntegerField(help_text='如：352', verbose_name='总千卡数')),
                ('total_elevation_gain', models.IntegerField(help_text='如：2', verbose_name='总爬升高度(米)')),
                ('average_power', models.IntegerField(help_text='如：117', verbose_name='平均功率(瓦)')),
                ('average_cadence', models.IntegerField(help_text='如：180', verbose_name='平均步频(步/分)')),
                ('average_pace', models.CharField(help_text='如：8:23', max_length=7, verbose_name='平均配速')),
                ('average_heart_rate', models.IntegerField(help_text='如：142', verbose_name='平均心率(次/分)')),
                ('average_stride_length', models.FloatField(help_text='如：0.7', verbose_name='平均步长(米)')),
                ('bottom_time', models.IntegerField(help_text='如：267', verbose_name='触底时间(毫秒)')),
                ('vertical_amplitude', models.FloatField(help_text='如：7.9', verbose_name='垂直振幅(厘米)')),
                ('five_pace', models.CharField(help_text='如：8:23,8:23,8:23,8:23,8:23', max_length=50, verbose_name='5段配速')),
                ('five_heart_rate', models.CharField(help_text='如：142,145,150,156,160', max_length=50, verbose_name='5段心率')),
                ('five_power', models.CharField(help_text='如：117,117,114,113,112', max_length=50, verbose_name='5段功率')),
                ('five_cadence', models.CharField(help_text='如：180,180,178,178,178', max_length=50, verbose_name='5段步频')),
                ('heart_rate', models.CharField(help_text='如：04:47,34:22,02:54,00:00,00:00', max_length=50, verbose_name='心率区间分布')),
            ],
            options={
                'verbose_name': '健身',
                'verbose_name_plural': '健身',
                'ordering': ['run_date'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='config_data',
            field=models.TextField(help_text='配置项作为全局上下文使用，上下文的具体定义见 apps/blog/context_processors.py 文件', verbose_name='配置数据'),
        ),
    ]
