# Generated by Django 2.2.28 on 2024-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20241012_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='location',
            field=models.CharField(default='深圳', max_length=50, verbose_name='位置'),
        ),
    ]
