# Generated by Django 2.2.28 on 2024-12-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_fitness_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='average_stride_length',
            field=models.FloatField(default=0.7, help_text='如：0.7', verbose_name='平均步长(米)'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='total_elevation_gain',
            field=models.IntegerField(default=2, help_text='如：2', verbose_name='总爬升高度(米)'),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='vertical_amplitude',
            field=models.FloatField(default=7.9, help_text='如：7.9', verbose_name='垂直振幅(厘米)'),
        ),
    ]
