# Generated by Django 2.2.28 on 2025-02-17 20:09

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20241211_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('description', models.CharField(max_length=250, verbose_name='描述')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='跳转地址')),
                ('sort_order', models.IntegerField(default=99, verbose_name='排序')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='subject/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', upload_to='subject/upload/project/%Y/%m/%d/', verbose_name='封面图')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['sort_order'],
            },
        ),
    ]
