# Generated by Django 2.2.28 on 2024-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('default_status', models.CharField(max_length=20)),
                ('common_usage', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
