# Generated by Django 2.2.28 on 2024-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['port_number'], 'verbose_name': '端口', 'verbose_name_plural': '端口'},
        ),
        migrations.AlterField(
            model_name='port',
            name='common_usage',
            field=models.CharField(max_length=200, verbose_name='使用场景'),
        ),
        migrations.AlterField(
            model_name='port',
            name='default_status',
            field=models.CharField(max_length=20, verbose_name='默认状态'),
        ),
        migrations.AlterField(
            model_name='port',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='port',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='port',
            name='port_number',
            field=models.IntegerField(verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='port',
            name='protocol',
            field=models.CharField(help_text='一般填写 TCP，UDP，TCP/UDP 等', max_length=10, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='port',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='服务名称'),
        ),
    ]
