# Generated by Django 2.2.28 on 2026-07-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('slug', models.SlugField(unique=True, verbose_name='URL标识')),
                ('description', models.TextField(verbose_name='说明文档（Markdown）')),
                ('code', models.TextField(verbose_name='脚本代码')),
                ('script_type', models.CharField(choices=[('shell', 'Shell'), ('python', 'Python')], default='shell', max_length=10, verbose_name='脚本类型')),
                ('filename', models.CharField(help_text='例如 install-docker.sh', max_length=100, verbose_name='下载文件名')),
                ('run_cmd', models.CharField(help_text='下载后的执行命令，例如 /bin/bash install-docker.sh -m', max_length=500, verbose_name='执行命令')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发布')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'ordering': ['-create_date'],
            },
        ),
    ]
