# Generated by Django 2.2.27 on 2023-04-23 11:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.png', upload_to='avatar/%Y/%m/%d/%H-%M-%S', verbose_name='头像'),
        ),
    ]
