# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20171230_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouser',
            name='link',
            field=models.URLField(blank=True, verbose_name='个人网址'),
        ),
    ]
