# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-30 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_ouser_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='link',
            field=models.URLField(blank=True, help_text='提示：网址以http开头', verbose_name='个人网址'),
        ),
    ]
