# Generated by Django 2.2.28 on 2024-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于看板中显示', max_length=30, unique=True, verbose_name='名称')),
                ('interval', models.IntegerField(default=5, help_text='上报间隔时间，超过这个时间的两倍还没有更新数据就标记为离线状态，单位：秒', verbose_name='上报间隔')),
                ('sort_order', models.IntegerField(default=99, help_text='自定义排序依据', verbose_name='排序')),
                ('push_url', models.CharField(help_text='客户端推送的地址，为了支持代理推送或者本地推送', max_length=60, verbose_name='推送地址')),
                ('username', models.CharField(help_text='推送用户名，唯一', max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='第一次添加后自动生成密钥，更改后会重新生成密钥', max_length=10, unique=True, verbose_name='密码')),
                ('secret_key', models.CharField(blank=True, help_text='保存后自动生成', max_length=64, null=True, verbose_name='加密Key')),
                ('secret_value', models.CharField(blank=True, help_text='保存后自动生成', max_length=256, null=True, verbose_name='密钥')),
                ('data', models.TextField(blank=True, help_text='json格式', null=True, verbose_name='上报数据')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控服务',
                'verbose_name_plural': '监控服务',
                'ordering': ['sort_order'],
            },
        ),
    ]
