# Generated by Django 2.2.28 on 2024-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitorserver_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorserver',
            name='alarm',
            field=models.BooleanField(default=False, help_text='默认不告警', verbose_name='是否告警'),
        ),
    ]
